version: "3"

services:
  django-app:
    container_name: django-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - environment:/app/.venv
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    restart: always
    image: postgres:14-alpine
    volumes:
      - .data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  environment:
